### ISSUE TITLE
Don't send mails with "Content-Type: multipart/mixed"

### ISSUE THREAD

**Issue by sschuberth** [rtyley/submitgit#17]
My patch as sent by submitgit has

    Content-Type: multipart/mixed;  boundary="----=_Part_8_836493213.1436462597065"

but @gitster [does not seem to like it](http://thread.gmane.org/gmane.comp.version-control.git/273758). Is there a way to just use a Content-Type of `text/plain`?

**Comment by gitster** [comment]
Does not seem to?  [No](http://thread.gmane.org/gmane.comp.version-control.git/273758/focus=273770).

The whole point of "submitgit" is to allow people to generate the common denominator format out of a commit pushed to GitHub.

Spewing anything but text/plain defeats the purpose of the system, I would have to say.

**Comment by rtyley** [comment]
At the moment submitGit sends email with a Content-Type header of `multipart/mixed`, containing a single MIME part which is `Content-Type: text/plain; charset=us-ascii`. There's no HTML part - that would get immediately bounced by vger.kernel.org - but there _is_ this unnecessary MIME wrapper, versus just having a plain text message.

Despite the MIME wrapper, the message still applies cleanly as a patch using 'git am' (ie if you download http://article.gmane.org/gmane.comp.version-control.git/273762/raw and apply it with 'git am a.patch') - so I'm assuming there's no functional problem here, it's just that we'd like to see the wrapper gone for the purity of conforming to the common format.

The MIME wrapper is there because I used the JavaMail API to construct the raw mail message, [as recommended](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html#send-email-raw-api) by the AWS SES docs. JavaMail actually doesn't have any implementation for producing simple plain-text messages - it only does MIME format! JavaMail underlies all the other JVM-based mail libraries I could find.

I'm slightly afraid of falling over on some encoding issue, but if the `Content-Type: multipart/mixed;` is as repugnant as it seems, I'm willing to take a crack at just doing all the header formatting code myself, and spitting the text out as a big text/plain string.

**Comment by sschuberth** [comment]
> JavaMail actually doesn't have any implementation for producing simple plain-text messages - it only does MIME format!

From reading the [MIME Wikipedia page](https://en.wikipedia.org/wiki/MIME#Content-Type) it seems to me as if using MIME is not wrong per se, we just shouldn't use MIME's *multipart* `Content-Type`.

At least the Wikipedia page for JavaMail claims to have an [example](https://en.wikipedia.org/wiki/JavaMail#Examples) that does "simple, single part, text/plain e-mail". Would that work for us?

**Comment by sschuberth** [comment]
Other than that, maybe looking into a Scala library like https://github.com/finagle/finagle-smtp would make sense?

**Comment by gitster** [comment]
"""Despite the MIME wrapper, the message still applies cleanly as a patch using 'git am' (ie if you download http://article.gmane.org/gmane.comp.version-control.git/273762/raw and apply it with 'git am a.patch') - so I'm assuming there's no functional problem here,..."""

That is a flawed argument. "git am" may accomodate a multi-part that happens to have a single text/plain in it, but "git am" is not the only thing that imposes policy restriction, and the git mailing list prefers a simple text/plain (not a multi-part). That is the common denominator format the tool should strive to produce.
