### ISSUE TITLE
Requests too excessive authorization

### ISSUE THREAD

**Issue by gitster** [rtyley/submitgit#2]
Maybe it is just me, but it feels that requesting read & write authorization for all public repositories of the user is way too excessive. If a user can live without the "I sent email using submitgit" breadcrumb left in his or her pull request, can't this be done only with read authorization on pull requests and nothing else?

Not that I'd be afraid that Roberto may go evil; more realistic and serious worry would be the service can be taken over by malicious crackers, whose evil deeds Roberto would not have any control over.

**Comment by rtyley** [comment]
That's a totally fair concern - at the moment, submitGit uses the
user's credentials for all things, including reading the PR from the
repo, so it needs 'repo' access - but there is no reason why it can't
read those public details with it's own credentials, and comment on
the PR with it's own account. I think the only required auth is the
remaining one to read the user's email details.

I think the one thing it won't be able to do is close the PR (which it
doesn't do at the moment anyway).

I'm on holiday at the moment, without a laptop, so will start work on
this stuff mid-next week. As it happens, I've found that the Gmail
android app on my phone always sends HTML, so can't easily reply to
the Git mailing list either at the moment!

**Comment by mhagger** [comment]
@rtyley I love this tool! Thanks for working on it!

Would there be advantages/disadvantages to creating a submitgit/git repo that is forked from git/git and owned by a `submitgit` org? Then you could have users submit PRs against *that* repo instead of directly against git/git?

The repo would be owned by a `submitgit` org with its own creds, making it possible to close PRs under its own authorization. It would also avoid the need for users to create PRs against git/git. Such PRs would be "dead" in the sense that no discussion is taking place there, and *if* discussion were added there it would usually be ignored, so having the PRs a little bit distant from git/git might be an advantage. On the other hand, the submitgit/git repo would be harder to find than git/git and people would have to select it as their PR base repository explicitly in most circumstances, adding a bit of friction.

I don't know...it was just a thought.

**Comment by rtyley** [comment]
Closing, because I think #3 addressed this.
