### ISSUE TITLE
Add a `From:` line when the author differs from the sender

### ISSUE THREAD

**Issue by dscho** [rtyley/submitgit#8]
In the [Git for Windows](https://github.com/git-for-windows/git) project, Windows-specific patches are often vetted for quite some time before being sent upstream. That means that yours truly sends patches that were actually authored by others, and of course I would like to keep the authorship intact.

The convention is to add a `From:` line to the top of the mail if sending along a patch from a different author. Would it be possible to teach SubmitGit to do that, too, when the author differs from the sender?

**Comment by rtyley** [comment]
> The convention is to add a From: line to the top of the mail if sending along a patch from a different author. Would it be possible to teach SubmitGit to do that, too, when the author differs from the sender?

Just to clarify, which of these two options do you mean:

1. the main `From:` header of the email
2. or instead an additional line in the body of the email? (please provide an example if so)

The first one is tricky to do, at least using my current mail-sending gateway, which is Amazon SES. Any `From:` or `Reply-To:` header in an email to be sent is only permitted if the e-mail has been validated as consenting to the process with Amazon SES. When you send the patchbomb on behalf of other people, we'd have to get them to validate their email addresses first in order to set that header.

...so I hope you mean the second option?

**Comment by gitster** [comment]
I am not dscho, but in-body From: is a fairly standard practice on git@vger mailing list; I am fairly certain that he meant 2.

For a recent example, see this one:

http://article.gmane.org/gmane.comp.version-control.git/271211/raw
